/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyWorker;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Pharmacy.Pharmacy;
import Business.Medicine.Medicine;
import Business.Medicine.MedicineDirectory;
import Business.Org.Organization;
import Business.Org.organizationDir;
import Business.Role.Doctor;
import Business.Role.LabTechRole;
import Business.Role.Nurse;
import Business.Role.Patient;
import Business.Role.ReceptionistRole;
import Business.Role.Role;
import Business.Utility.Validation;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshita
 */
public class ManageMedicinesJPanel extends javax.swing.JPanel {

    private organizationDir organizationDir;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private MedicineDirectory medicineDir;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageMedicinesJPanel(JPanel userProcessContainer,organizationDir organizationDir, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        this.enterprise= enterprise;
        this.medicineDir= ((Pharmacy)enterprise).getMedicineList();
        //populateMainMedicineComboBox();
        //populateOrganizationEmpComboBox();
        viewMedicineJPanel.setVisible(false);
        addMedicineJPanel.setVisible(false);
    }
    
    public void populateOrganizationComboBox(){
        cmbMainMedicineType.removeAllItems();
        
        for (Organization organization : organizationDir.getOrgList()){
            cmbMainMedicineType.addItem(organization);
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        cmbMedicineType.removeAllItems();
        Organization organization = (Organization) cmbMainMedicineType.getSelectedItem();
        List<Role> rolesList = organization.getSupportedRole();
        
        
        for (Role role : rolesList){
           
            cmbMedicineType.addItem(role.roleValue());
        }
    }

    private void populateTable(String medType){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        String date1=null;
        SimpleDateFormat formatter1=new SimpleDateFormat("yyyy-MM-dd");
        for (Medicine med : medicineDir.getList()){
            if(med.getType().equals(medType))
            {
            
            Object[] row = new Object[6];
            row[0] = med;//.getId();
            row[1] = med.getName();
            row[2] = med.getDosage();
            row[3] = med.getQuantity();
            row[4] = med.getType();
            
            
            try {
               date1 =formatter1.format(med.getExpiryDate());
            } catch (Exception ex) {
                System.out.println("Error in ManageMedicineJPanel view panel for date paring");
                Logger.getLogger(ManageMedicinesJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            row[5] = date1;
            model.addRow(row);
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        cmbMainMedicineType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        addMedicineJPanel = new javax.swing.JPanel();
        dosageJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        cmbMedicineType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        availableQtyTxt = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        expDate = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        viewMedicineJPanel = new javax.swing.JPanel();
        dosageJTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priceTxt1 = new javax.swing.JTextField();
        nameJTextField1 = new javax.swing.JTextField();
        cmbMedicineType1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        availableQtyTxt1 = new javax.swing.JTextField();
        btnSave1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        closebtn1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        expDate1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setBackground(new java.awt.Color(255, 193, 131));
        organizationJTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        organizationJTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Dosage", "Quantity", "Type", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        organizationJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(organizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 641, 190));

        cmbMainMedicineType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbMainMedicineType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Liquid", "Tablet", "Gel", "Injection", "Other" }));
        cmbMainMedicineType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMainMedicineTypeActionPerformed(evt);
            }
        });
        add(cmbMainMedicineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 179, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Medicine Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        addMedicineJPanel.setBackground(new java.awt.Color(255, 255, 255));
        addMedicineJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Medicine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(68, 145, 157))); // NOI18N

        dosageJTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Price");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        priceTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        nameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cmbMedicineType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbMedicineType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Liquid", "Tablet", "Gel", "Injection", "Other" }));
        cmbMedicineType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicineTypeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Type");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Dosage");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Available Unit");

        availableQtyTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnSave.setBackground(new java.awt.Color(102, 147, 255));
        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        closebtn.setBackground(new java.awt.Color(102, 147, 255));
        closebtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Expiry Date");

        expDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout addMedicineJPanelLayout = new javax.swing.GroupLayout(addMedicineJPanel);
        addMedicineJPanel.setLayout(addMedicineJPanelLayout);
        addMedicineJPanelLayout.setHorizontalGroup(
            addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMedicineJPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addMedicineJPanelLayout.createSequentialGroup()
                        .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(availableQtyTxt)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMedicineJPanelLayout.createSequentialGroup()
                        .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(68, 68, 68)
                        .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dosageJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMedicineType, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMedicineJPanelLayout.createSequentialGroup()
                        .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closebtn)
                            .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        addMedicineJPanelLayout.setVerticalGroup(
            addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMedicineJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMedicineJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(cmbMedicineType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dosageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(availableQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(addMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closebtn)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(addMedicineJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 370));

        jPanel1.setBackground(new java.awt.Color(196, 224, 229));

        btnAdd.setBackground(new java.awt.Color(255, 155, 54));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setText("Add Medicine");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(255, 155, 54));
        btnView.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 170, 170, 220));

        viewMedicineJPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewMedicineJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Medicine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(68, 145, 157))); // NOI18N

        dosageJTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Price");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Name");

        priceTxt1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        nameJTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cmbMedicineType1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbMedicineType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Liquid", "Tablet", "Gel", "Injection", "Other" }));
        cmbMedicineType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicineType1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Type");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Dosage");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Available Unit");

        availableQtyTxt1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnSave1.setBackground(new java.awt.Color(102, 147, 255));
        btnSave1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        btnUpdate1.setBackground(new java.awt.Color(102, 147, 255));
        btnUpdate1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUpdate1.setText("Update Details");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        closebtn1.setBackground(new java.awt.Color(102, 147, 255));
        closebtn1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        closebtn1.setText("Close");
        closebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtn1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Expiry Date");

        expDate1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout viewMedicineJPanelLayout = new javax.swing.GroupLayout(viewMedicineJPanel);
        viewMedicineJPanel.setLayout(viewMedicineJPanelLayout);
        viewMedicineJPanelLayout.setHorizontalGroup(
            viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMedicineJPanelLayout.createSequentialGroup()
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewMedicineJPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(viewMedicineJPanelLayout.createSequentialGroup()
                                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9))
                                .addGap(33, 33, 33)
                                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(availableQtyTxt1)
                                    .addComponent(priceTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewMedicineJPanelLayout.createSequentialGroup()
                                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(68, 68, 68)
                                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nameJTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dosageJTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMedicineType1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewMedicineJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(expDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewMedicineJPanelLayout.createSequentialGroup()
                                .addComponent(btnSave1)
                                .addGap(45, 45, 45)
                                .addComponent(btnUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(viewMedicineJPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(closebtn1)))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        viewMedicineJPanelLayout.setVerticalGroup(
            viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMedicineJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewMedicineJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(cmbMedicineType1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dosageJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(availableQtyTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(14, 14, 14)
                .addGroup(viewMedicineJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave1)
                    .addComponent(btnUpdate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(closebtn1)
                .addContainerGap())
        );

        add(viewMedicineJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, 370));

        jPanel14.setBackground(new java.awt.Color(196, 224, 229));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jPanel13.setBackground(new java.awt.Color(68, 145, 157));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(68, 145, 157));
        jLabel15.setText("Manage Medicine Inventory");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 310, 37));

        backJButton.setBackground(new java.awt.Color(102, 147, 255));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.setPreferredSize(new java.awt.Dimension(100, 40));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 103, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
       String name= nameJTextField.getText();
       String dosage = dosageJTextField.getText();
       String qty = availableQtyTxt.getText();
       String type= (String) cmbMedicineType.getSelectedItem();
       String date = expDate.getText();       
       String priceString = priceTxt.getText();
        
       if(name ==  null || name.equals("")
               || 
               dosage ==  null || dosage.equals("")
               ||
               qty ==  null || qty.equals("")
               ||
               type ==  null || type.equals("")
               ||
               date ==  null || date.equals("")
               ||
               priceString ==  null || priceString.equals("")
               
               )
       {
            JOptionPane.showMessageDialog(null, "Please enter all details","Warning",JOptionPane.WARNING_MESSAGE);
            return;
       }
       
       //validation on data
       boolean valid = Validation.validateString(name);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter name correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       valid = Validation.validateNumeric(dosage);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter dosage correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       
       valid = Validation.validateNumeric(qty);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter quantity correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       valid = Validation.validateDate(date);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter date correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       valid = Validation.validateNumeric(dosage);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter price correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       
       //parse
           
        int quantity =  Integer.parseInt(qty);
        double price = Double.parseDouble(priceString);
        
        if(price == 0.0)
        {
            JOptionPane.showMessageDialog(null, "Please enter price correctly, cannot be zero","Warning",JOptionPane.WARNING_MESSAGE);
           return;
            
        }
        //Date parse
       
        Date date1=null;
        SimpleDateFormat formatter1=new SimpleDateFormat("yyyy-MM-dd");
        try {
           date1 =formatter1.parse(date);
        } catch (ParseException ex) {
            System.out.println("Error in ManageMedicineJPanel for date paring");
            Logger.getLogger(ManageMedicinesJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Medicine medicine = new Medicine();
        medicine.setDosage(dosage);
        medicine.setExpiryDate(date1);
        medicine.setName(name);
        medicine.setPrice(price);
        medicine.setQuantity(quantity);
        medicine.setType(type);
        //Add to dir           
        medicineDir.getList().add(medicine);
        
        
        JOptionPane.showMessageDialog(null, "Added successfully","Information",JOptionPane.INFORMATION_MESSAGE);
         
        
       //populate table by using main medicine cmb box 
        String medType = (String) cmbMainMedicineType.getSelectedItem();
        populateTable(medType);
        
        nameJTextField.setText("");
        dosageJTextField.setText("");
      availableQtyTxt.setText("");
       //cmbMedicineType.setSelectedItem(med.getType());
        expDate.setText("");       
         priceTxt.setText("");
        
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    
    public Role createObjectForRole(String roleString){
        Role role = null;
        if(roleString.equals("DoctorRole"))
        {
            role=new Doctor();
        }
        else if(roleString.equals("NurseRole"))
        {
            role=new Nurse();
        }
        else if(roleString.equals("LabTechnicianRole"))
        {
            role=new LabTechRole();
        }
        else if(roleString.equals("PatientRole"))
        {
            role=new Patient();
        }
        else if(roleString.equals("ReceptionistRole"))
        {
            role=new ReceptionistRole();
        }
        
        return role;
    }
    
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cmbMedicineTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicineTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMedicineTypeActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        addMedicineJPanel.setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    private void cmbMainMedicineTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMainMedicineTypeActionPerformed
        String medType = (String) cmbMainMedicineType.getSelectedItem();
        if (medicineDir != null && !medicineDir.getList().isEmpty()){
            populateTable(medType);
            //populateOrganizationEmpComboBox();  //based on organization seleted, get the supported roles only
        }
    }//GEN-LAST:event_cmbMainMedicineTypeActionPerformed

    private void cmbMedicineType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicineType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMedicineType1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        
        String name= nameJTextField1.getText();
       String dosage = dosageJTextField1.getText();
       String qty = availableQtyTxt1.getText();
       String type= (String) cmbMedicineType1.getSelectedItem();
       String date = expDate1.getText();       
       String priceString = priceTxt1.getText();
        
       if(name ==  null || name.equals("")
               || 
               dosage ==  null || dosage.equals("")
               ||
               qty ==  null || qty.equals("")
               ||
               type ==  null || type.equals("")
               ||
               date ==  null || date.equals("")
               ||
               priceString ==  null || priceString.equals("")
               
               )
       {
            JOptionPane.showMessageDialog(null, "Please enter all details","Warning",JOptionPane.WARNING_MESSAGE);
            return;
       }
       
       //validation on data
       boolean valid = Validation.stringValidator(name);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter name correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       valid = Validation.validateNumeric(dosage);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter dosage correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       
       valid = Validation.validateNumeric(qty);
       if(valid == false )
       {
           JOptionPane.showMessageDialog(null, "Please enter quantity correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       valid = Validation.validateDate(date);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter date correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       valid = Validation.validateNumeric(dosage);
       if(valid == false)
       {
           JOptionPane.showMessageDialog(null, "Please enter price correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       
       //parse
           
        int quantity =  Integer.parseInt(qty);
        
        if(quantity <0)
        {
            JOptionPane.showMessageDialog(null, "Please enter quantity correctly","Warning",JOptionPane.WARNING_MESSAGE);
           return;
            
        }
        
        double price = Double.parseDouble(priceString);
        if(price == 0.0)
        {
            JOptionPane.showMessageDialog(null, "Please enter price correctly, cannot be zero","Warning",JOptionPane.WARNING_MESSAGE);
           return;
            
        }
        //Date parse
       
        Date date1=null;
        SimpleDateFormat formatter1=new SimpleDateFormat("yyyy-MM-dd");
        try {
           date1 =formatter1.parse(date);
        } catch (ParseException ex) {
            System.out.println("Error in ManageMedicineJPanel view panel for date paring");
            Logger.getLogger(ManageMedicinesJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int row = organizationJTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Medicine medicine= (Medicine)  organizationJTable.getValueAt(row,0);
        medicine.setDosage(dosage);
        medicine.setExpiryDate(date1);
        medicine.setName(name);
        medicine.setPrice(price);
        medicine.setQuantity(quantity);
        medicine.setType(type);
                 
       // medicineDir.getMedicineList().add(medicine);
        
        
        JOptionPane.showMessageDialog(null, "Updated successfully","Information",JOptionPane.INFORMATION_MESSAGE);
         
        
       //populate table by using main medicine cmb box 
        String medType = (String) cmbMainMedicineType.getSelectedItem();
        populateTable(medType);
        
        
        cmbMedicineType1.setEnabled(false);
        nameJTextField1.setEditable(false);
        dosageJTextField1.setEditable(false);
        availableQtyTxt1.setEditable(false);
          expDate1.setEditable(false);      
           priceTxt1.setEditable(false);     
         btnSave1.setEnabled(false);
           btnUpdate1.setEnabled(true);   
        
        
        
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void closebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtn1ActionPerformed
        // TODO add your handling code here:
        viewMedicineJPanel.setVisible(false);
    }//GEN-LAST:event_closebtn1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addMedicineJPanel.setVisible(true);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        
        cmbMedicineType1.setEnabled(true);
        nameJTextField1.setEditable(true);
        dosageJTextField1.setEditable(true);
        availableQtyTxt1.setEditable(true);
          expDate1.setEditable(true);      
           priceTxt1.setEditable(true); 
           btnSave1.setEnabled(true);
           btnUpdate1.setEnabled(false);
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
          int row = organizationJTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        viewMedicineJPanel.setVisible(true);
        
        //populate 
        Medicine med= (Medicine)  organizationJTable.getValueAt(row,0);
        populateViewMedicine(med);
    }//GEN-LAST:event_btnViewActionPerformed

    
    void populateViewMedicine(Medicine med){
        
        nameJTextField1.setText(med.getName());
        dosageJTextField1.setText(med.getDosage());
      availableQtyTxt1.setText(String.valueOf(med.getQuantity()));
       cmbMedicineType1.setSelectedItem(med.getType());
       
       String date1=null;
        SimpleDateFormat formatter1=new SimpleDateFormat("yyyy-MM-dd");
        try {
           date1 =formatter1.format(med.getExpiryDate());
        } catch (Exception ex) {
            System.out.println("Error in ManageMedicineJPanel for date paring");
            Logger.getLogger(ManageMedicinesJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        expDate1.setText(date1);       
         priceTxt1.setText(String.valueOf(med.getPrice()));
        
        cmbMedicineType1.setEnabled(false);
        nameJTextField1.setEditable(false);
        dosageJTextField1.setEditable(false);
        availableQtyTxt1.setEditable(false);
          expDate1.setEditable(false);      
           priceTxt1.setEditable(false);     
         btnSave1.setEnabled(false);
           btnUpdate1.setEnabled(true);        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addMedicineJPanel;
    private javax.swing.JTextField availableQtyTxt;
    private javax.swing.JTextField availableQtyTxt1;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnView;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton closebtn1;
    private javax.swing.JComboBox cmbMainMedicineType;
    private javax.swing.JComboBox cmbMedicineType;
    private javax.swing.JComboBox cmbMedicineType1;
    private javax.swing.JTextField dosageJTextField;
    private javax.swing.JTextField dosageJTextField1;
    private javax.swing.JTextField expDate;
    private javax.swing.JTextField expDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField priceTxt1;
    private javax.swing.JPanel viewMedicineJPanel;
    // End of variables declaration//GEN-END:variables
}
