/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysAdmin;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.Administrator.AppointmentStatusGraphNetwork;
import userinterface.Administrator.AppointmentTypeGraph;
import userinterface.Administrator.TotalBedCountGraph;

/**
 *
 * @author harshita
 */
public class ManageNetworks extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworks(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateNetworkTable();
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        networkTable = new javax.swing.JTable();
        submitBtn = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnViewGraph = new javax.swing.JButton();
        btnViewGraph1 = new javax.swing.JButton();
        btnViewApptntStatus = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        networkTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, null));
        networkTable.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        networkTable.setForeground(new java.awt.Color(0, 0, 153));
        networkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Network Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        networkTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(networkTable);
        if (networkTable.getColumnModel().getColumnCount() > 0) {
            networkTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 270, 190));

        submitBtn.setBackground(new java.awt.Color(0, 0, 153));
        submitBtn.setFont(new java.awt.Font("Kannada MN", 0, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        nameTextField.setBackground(new java.awt.Color(255, 204, 0));
        nameTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nameTextField.setBorder(null);
        nameTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nameTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 140, 30));

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Create a network");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, 34));

        jPanel13.setBackground(new java.awt.Color(68, 145, 157));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, -1));

        jLabel12.setFont(new java.awt.Font("Kannada MN", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Manage Networks");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 350, 50));

        btnViewGraph.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnViewGraph.setPreferredSize(new java.awt.Dimension(167, 40));
        btnViewGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGraphActionPerformed(evt);
            }
        });
        add(btnViewGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, 40));

        btnViewGraph1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnViewGraph1.setPreferredSize(new java.awt.Dimension(167, 40));
        btnViewGraph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGraph1ActionPerformed(evt);
            }
        });
        add(btnViewGraph1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 80, 40));

        btnViewApptntStatus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnViewApptntStatus.setPreferredSize(new java.awt.Dimension(167, 40));
        btnViewApptntStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewApptntStatusActionPerformed(evt);
            }
        });
        add(btnViewApptntStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 230, -1));

        jPanel15.setBackground(new java.awt.Color(68, 145, 157));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1501077931-network.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 990, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

        if(nameTextField.getText()==null || nameTextField.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Enter network name!");
            return;
        }
        String name = nameTextField.getText();

        //check network unique
        
        for(Network net: system.getNetworkList())
        {
            if(net.getName().equalsIgnoreCase(name))
            {
                  JOptionPane.showMessageDialog(null, "Network already exists!");
            return;
            }
        }
        
        
        Network network = system.createAndAddNetwork();
        network.setName(name);
        nameTextField.setText("");
        populateNetworkTable();
        
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Network added successfully!");
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminMainPanel sysAdminwjp = (SysAdminMainPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnViewGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGraphActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = networkTable.getSelectedRow();
        
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a Network to show Bed Graph!");
            return;
        }
        
        DefaultTableModel bedModel = (DefaultTableModel) networkTable.getModel();
        Network selectedNetwork = (Network) bedModel.getValueAt(selectedRowIndex, 0);
        
        TotalBedCountGraph manageOrganizationJPanel = new TotalBedCountGraph(userProcessContainer, system,selectedNetwork);
        userProcessContainer.add("TotalBedCountGraph1", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewGraphActionPerformed

    private void btnViewGraph1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGraph1ActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = networkTable.getSelectedRow();
        
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a Network to show Appointment Type Graph!");
            return;
        }
        
        DefaultTableModel bedModel = (DefaultTableModel) networkTable.getModel();
        Network selectedNetwork = (Network) bedModel.getValueAt(selectedRowIndex, 0);
        
        AppointmentTypeGraph manageOrganizationJPanel = new AppointmentTypeGraph(userProcessContainer, system, selectedNetwork );
        userProcessContainer.add("AppointmentTypeGraph", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewGraph1ActionPerformed

    private void btnViewApptntStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewApptntStatusActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = networkTable.getSelectedRow();
        
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a Network to show Appointment Status Graph!");
            return;
        }
        
        DefaultTableModel bedModel = (DefaultTableModel) networkTable.getModel();
        Network selectedNetwork = (Network) bedModel.getValueAt(selectedRowIndex, 0);

        AppointmentStatusGraphNetwork manageOrganizationJPanel = new AppointmentStatusGraphNetwork(userProcessContainer, system, selectedNetwork);
        userProcessContainer.add("AppointmentStatusGraphALLENTERPISE", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewApptntStatusActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnViewApptntStatus;
    private javax.swing.JButton btnViewGraph;
    private javax.swing.JButton btnViewGraph1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTable networkTable;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
