/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Appointment.Appointment;
import Business.Appointment.Prescription;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Org.Organization;
import Business.Patient.Patients;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class ViewPrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPrescriptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    private Appointment appointment;
    private Patients patient;
    private Employee doctor;
    
    public ViewPrescriptionJPanel( JPanel userProcessContainer, UserAccount userAccount,Organization organization,Enterprise enterprise,EcoSystem ecosystem, Appointment appointment, Patients patient, Employee doctor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
       this.enterprise= enterprise;
       this.ecosystem = ecosystem;
       this.appointment = appointment;
       this.patient = patient;
       this.doctor= doctor;
       Prescription prescription = appointment.getPrescrption();
       populatePrescription();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        viewPrescriptionTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewPrescriptionTbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        viewPrescriptionTbl.setFont(new java.awt.Font("Trattatello", 1, 14)); // NOI18N
        viewPrescriptionTbl.setForeground(new java.awt.Color(255, 204, 204));
        viewPrescriptionTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient", "Doctor", "Medicines", "Dosage", "Pharmacy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(viewPrescriptionTbl);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 420, 370));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Prescription");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.setPreferredSize(new java.awt.Dimension(100, 40));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Doctor/image copy.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));
    }// </editor-fold>//GEN-END:initComponents

    public void populatePrescription(){
         DefaultTableModel model = (DefaultTableModel) viewPrescriptionTbl.getModel();
        model.setRowCount(0);
        Prescription prelist = appointment.getPrescrption();
        
        
        for (Map.Entry<Medicine, Double> entry : appointment.getPrescrption().getMedsPrescribed().entrySet()){
         Object[] row = new Object[5];
            row[0] = patient.getEmpName();
            row[1] = doctor.getEmpName();
            row[2] = entry.getKey();
            row[3] = entry.getValue();
            row[4] = prelist.getPharmacy().getName();
            model.addRow(row);
    }
        }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable viewPrescriptionTbl;
    // End of variables declaration//GEN-END:variables
}
